bazel_dep(name = "rules_pylyglot", version = "0.0.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.9.0", dev_dependency = True)
bazel_dep(name = "rules_python", version = "2.3.2", dev_dependency = True)

local_path_override(
    module_name = "rules_pylyglot",
    path = "../..",
)
