#!/usr/bin/env python3
"""Builds deterministic text-only Python bundles and launchers."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

_MARKER = "# __PYLYGLOT_PAYLOAD__\n"

_BOOTSTRAP = (
    "import pathlib,sys;"
    "p=pathlib.Path(sys.argv[1]);"
    "m=(b'\\n# __PYLYGLOT_'+b'PAYLOAD__\\n');"
    "s=p.read_bytes().rsplit(m,1)[1];"
    "sys.argv=sys.argv[1:];"
    "g=sys.modules['__main__'].__dict__;"
    "g.update(__file__=str(p),__package__=None,__cached__=None);"
    "exec(compile(s,str(p),'exec'),g)"
)


def _bytes_expression(data: bytes, indent: str = "    ") -> str:
    lines = data.splitlines(keepends=True)
    if not lines:
        return "b''"
    if len(lines) == 1:
        return repr(lines[0])
    return "(\n{}\n)".format("\n".join(f"{indent}{line!r}" for line in lines))


def _payload(manifest: dict[str, Any]) -> str:
    chunks = [
        "#!/usr/bin/env python3\n",
        "# Generated by rules_pylyglot. Do not edit.\n",
        "import importlib.abc as _pylyglot_abc\n",
        "import importlib.util as _pylyglot_util\n",
        "import sys as _pylyglot_sys\n\n",
        "_PYLYGLOT_MODULES = {}\n",
    ]

    for module in manifest["modules"]:
        source = Path(module["path"]).read_bytes()
        record = (
            f"({_bytes_expression(source, indent='        ')}, "
            f"{module['origin']!r}, {module['is_package']!r})"
        )
        chunks.append(f"_PYLYGLOT_MODULES[{module['name']!r}] = {record}\n")

    chunks.extend(
        [
            "\n",
            "class _PylyglotLoader(_pylyglot_abc.Loader):\n",
            "    def create_module(self, spec):\n",
            "        return None\n\n",
            "    def exec_module(self, module):\n",
            "        source, origin, _ = _PYLYGLOT_MODULES[module.__name__]\n",
            "        module.__file__ = origin\n",
            "        exec(compile(source, origin, 'exec'), module.__dict__)\n\n",
            "\n",
            "class _PylyglotFinder(_pylyglot_abc.MetaPathFinder):\n",
            "    def __init__(self):\n",
            "        self.loader = _PylyglotLoader()\n\n",
            "    def find_spec(self, fullname, path=None, target=None):\n",
            "        record = _PYLYGLOT_MODULES.get(fullname)\n",
            "        if record is None:\n",
            "            return None\n",
            "        _, origin, is_package = record\n",
            "        return _pylyglot_util.spec_from_loader(\n",
            "            fullname,\n",
            "            self.loader,\n",
            "            origin=origin,\n",
            "            is_package=is_package,\n",
            "        )\n\n",
            "\n",
            "_pylyglot_sys.meta_path.insert(0, _PylyglotFinder())\n",
        ],
    )

    main = manifest["main"]
    main_source = Path(main["path"]).read_bytes()
    chunks.extend(
        [
            f"_PYLYGLOT_MAIN = {_bytes_expression(main_source)}\n",
            "_pylyglot_globals = _pylyglot_sys.modules['__main__'].__dict__\n",
            "_pylyglot_globals.update(\n",
            "    __name__='__main__',\n",
            f"    __file__={main['origin']!r},\n",
            f"    __package__={main['package']!r} or None,\n",
            "    __cached__=None,\n",
            "    __spec__=None,\n",
            ")\n",
            f"exec(compile(_PYLYGLOT_MAIN, {main['origin']!r}, 'exec'), "
            "_pylyglot_globals)\n",
        ],
    )
    return "".join(chunks)


def _posix_launcher(payload_name: str) -> str:
    return f"""#!/bin/sh
script_dir=$(CDPATH= cd -P "$(dirname "$0")" >/dev/null 2>&1 && pwd)
payload="$script_dir/{payload_name}"
if command -v python3 >/dev/null 2>&1; then
    exec python3 "$payload" "$@"
elif command -v python >/dev/null 2>&1; then
    exec python "$payload" "$@"
fi
echo "Error: Python interpreter not found on PATH." >&2
exit 1
"""


def _windows_commands(script: str, *, self_contained: bool) -> str:
    if self_contained:
        py_args = f'-c "{_BOOTSTRAP}" "%~f0" %*'
    else:
        py_args = f'"%~dp0{script}" %*'
    return f"""@echo off
@where py >nul 2>nul
@if errorlevel 1 goto pylyglot_python3
@py -3 -c "import sys;raise SystemExit(sys.version_info[0] != 3)" >nul 2>nul
@if errorlevel 1 goto pylyglot_python3
@py -3 {py_args}
@exit /b %errorlevel%
:pylyglot_python3
@where python3 >nul 2>nul
@if errorlevel 1 goto pylyglot_python
@python3 -c "import sys;raise SystemExit(sys.version_info[0] != 3)" >nul 2>nul
@if errorlevel 1 goto pylyglot_python
@python3 {py_args}
@exit /b %errorlevel%
:pylyglot_python
@where python >nul 2>nul
@if errorlevel 1 goto pylyglot_missing
@python -c "import sys;raise SystemExit(sys.version_info[0] != 3)" >nul 2>nul
@if errorlevel 1 goto pylyglot_missing
@python {py_args}
@exit /b %errorlevel%
:pylyglot_missing
@echo Error: Python interpreter not found on PATH. 1>&2
@exit /b 1
"""


def _polyglot_launcher(*, posix_first: bool) -> str:
    first_line = "#!/bin/sh\n" if posix_first else ""
    batch = _windows_commands("", self_contained=True)
    return (
        first_line
        + ": <<'PYLYGLOT_BATCH'\n"
        + batch
        + "PYLYGLOT_BATCH\n"
        + "if command -v python3 >/dev/null 2>&1; then\n"
        + f'    exec python3 -c "{_BOOTSTRAP}" "$0" "$@"\n'
        + "elif command -v python >/dev/null 2>&1; then\n"
        + f'    exec python -c "{_BOOTSTRAP}" "$0" "$@"\n'
        + "fi\n"
        + 'echo "Error: Python interpreter not found on PATH." >&2\n'
        + "exit 1\n"
    )


def _write(path: str, content: str, *, executable: bool) -> None:
    output = Path(path)
    output.write_bytes(content.encode("utf-8"))
    if executable:
        os.chmod(output, 0o755)


def bundle(manifest: dict[str, Any]) -> None:
    payload = _payload(manifest)
    outputs = manifest["outputs"]
    style = manifest["style"]

    if style == "multiplat":
        payload_path = outputs["payload"]
        payload_name = Path(payload_path).name
        _write(payload_path, payload, executable=True)
        _write(
            outputs["posix"],
            _posix_launcher(payload_name),
            executable=True,
        )
        _write(
            outputs["windows"],
            _windows_commands(payload_name, self_contained=False),
            executable=False,
        )
        return

    if style not in {"posix_first", "windows_first"}:
        raise ValueError(f"Unknown bundle style: {style}")
    launcher = _polyglot_launcher(posix_first=style == "posix_first")
    _write(
        outputs["posix"],
        launcher + "\n" + _MARKER + payload,
        executable=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    args = parser.parse_args()
    with open(args.manifest, encoding="utf-8") as manifest_file:
        manifest = json.load(manifest_file)
    bundle(manifest)


if __name__ == "__main__":
    main()
